CC=mpicc
CFLAGS=-std=c++11

all:
	$(CC) $(CFLAGS) -o MMrotateArotateB MMrotateArotateB.cpp
	$(CC) $(CFLAGS) -o MMrotateAbroadcastB MMrotateAbroadcastB.cpp
	$(CC) $(CFLAGS) -o MMbroadcastAbroadcastB MMbroadcastAbroadcastB.cpp

clean:
	rm -rf MMrotateArotateB MMrotateAbroadcastB MMbroadcastAbroadcastB
