CC=mpicc
CFLAGS=-std=c++11
CFLAGS1=-O0

all:
	$(CC) $(CFLAGS) $(CFLAGS) -o MMbroadcastAbroadcastB_partA_changed MMbroadcastAbroadcastB_partA_changed.cpp
	$(CC) $(CFLAGS) $(CFLAGS) -o MMbroadcastAbroadcastB_partD_changed MMbroadcastAbroadcastB_partD_changed.cpp

clean:
	rm -rf MMbroadcastAbroadcastB_partA_changed MMbroadcastAbroadcastB_partD_changed
